In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("../Dataset/Sample_dataset.csv")

### Data Exploration

In [3]:
df.head()

,OrderID,OrderDate,Product,Category,Quantity,Sales,Region,PaymentMethod,OrderStatus
0,1,1/2/2025,Mouse,Electronics,5,3778.0,South,UPI,Completed
1,2,1/3/2025,Phone,electronics,9,13934.0,North,Credit Card,Pending
2,3,1/4/2025,Keyboard,Electronics,1,4665.0,North,Debit Card,Completed
3,4,1/5/2025,Phone,electronics,10,66737.0,North,Cash,Cancelled
4,5,1/6/2025,Keyboard,electronics,7,71926.0,South,Net Banking,Completed

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1030 entries, 0 to 1029
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   OrderID        1030 non-null   int64
 1   OrderDate      1030 non-null   str
 2   Product        1002 non-null   str
 3   Category       1030 non-null   str
 4   Quantity       1030 non-null   int64
 5   Sales          1006 non-null   float64
 6   Region         1030 non-null   str
 7   PaymentMethod  1029 non-null   str
 8   OrderStatus    1029 non-null   str
dtypes: float64(1), int64(2), str(6)
memory usage: 72.6 KB

In [5]:
df.describe()

           OrderID     Quantity         Sales
count  1030.000000  1030.000000   1006.000000
mean    487.830097     5.462136  41349.780318
std     293.841725     2.871397  23111.989701
min       1.000000     1.000000    642.000000
25%     228.250000     3.000000  20913.500000
50%     485.500000     5.000000  41830.500000
75%     742.750000     8.000000  61486.500000
max    1000.000000    10.000000  79982.000000

In [6]:
df.duplicated().sum()

np.int64(30)

In [7]:
df.isnull().sum()

OrderID           0
OrderDate         0
Product          28
Category          0
Quantity          0
Sales            24
Region            0
PaymentMethod     1
OrderStatus       1
dtype: int64

In [21]:
columns = ["Product", "Category", "Region", "PaymentMethod", "OrderStatus"]

for col in columns:
    print(f"\n{col}:")
    print(df[col].unique())

Product:
<StringArray>
['Mouse', 'Phone', 'Keyboard', 'Monitor', 'Tablet', 'Laptop', 'Unknown']
Length: 7, dtype: str

Category:
<StringArray>
['Electronics', 'electronics', ' ELECTRONICS ']
Length: 3, dtype: str

Region:
<StringArray>
['South', 'North', 'West', 'East']
Length: 4, dtype: str

PaymentMethod:
<StringArray>
['UPI', 'Credit Card', 'Debit Card', 'Cash', 'Net Banking', 'upi']
Length: 6, dtype: str

OrderStatus:
<StringArray>
['Completed', 'Pending', 'Cancelled', 'completed', 'COMPLETED']
Length: 5, dtype: str

### Data Cleaning

In [14]:
df = df.drop_duplicates()

In [15]:
df["Sales"] = df["Sales"].fillna(df["Sales"].mean())

df["Product"] = df["Product"].fillna("Unknown")

df["PaymentMethod"] = df["PaymentMethod"].fillna(df["PaymentMethod"].mode()[0])

df["OrderStatus"] = df["OrderStatus"].fillna(df["OrderStatus"].mode()[0])

In [19]:
df.isnull().sum()

OrderID          0
OrderDate        0
Product          0
Category         0
Quantity         0
Sales            0
Region           0
PaymentMethod    0
OrderStatus      0
dtype: int64

In [18]:
df.duplicated().sum()

np.int64(0)

In [22]:
df["Category"] = df["Category"].str.strip().str.title()

df["PaymentMethod"] = df["PaymentMethod"].str.strip().str.title()

df["OrderStatus"] = df["OrderStatus"].str.strip().str.title()

In [23]:
columns = ["Product", "Category", "Region", "PaymentMethod", "OrderStatus"]

for col in columns:
    print(f"\n{col}:")
    print(df[col].unique())

Product:
<StringArray>
['Mouse', 'Phone', 'Keyboard', 'Monitor', 'Tablet', 'Laptop', 'Unknown']
Length: 7, dtype: str

Category:
<StringArray>
['Electronics']
Length: 1, dtype: str

Region:
<StringArray>
['South', 'North', 'West', 'East']
Length: 4, dtype: str

PaymentMethod:
<StringArray>
['Upi', 'Credit Card', 'Debit Card', 'Cash', 'Net Banking']
Length: 5, dtype: str

OrderStatus:
<StringArray>
['Completed', 'Pending', 'Cancelled']
Length: 3, dtype: str

In [25]:
df.to_csv("../Reports/Cleaned_data.csv", index=False)

In [26]:
df.head()

,OrderID,OrderDate,Product,Category,Quantity,Sales,Region,PaymentMethod,OrderStatus
0,1,1/2/2025,Mouse,Electronics,5,3778.0,South,Upi,Completed
1,2,1/3/2025,Phone,Electronics,9,13934.0,North,Credit Card,Pending
2,3,1/4/2025,Keyboard,Electronics,1,4665.0,North,Debit Card,Completed
3,4,1/5/2025,Phone,Electronics,10,66737.0,North,Cash,Cancelled
4,5,1/6/2025,Keyboard,Electronics,7,71926.0,South,Net Banking,Completed